### ISSUE TITLE
object has no attribute '_memoizedcall' on pytest 6.x

### ISSUE THREAD

**Issue by b0g3r** [pytest-dev/pytest-describe#34] opened 2020-10-17 15:40 UTC
Hi there! I started to use your library for one of my new projects and faced up with the exception like this:

```
tests/api/personal/test_change_password.py:None (tests/api/personal/test_change_password.py)
.venv/lib/python3.9/site-packages/pytest_describe/plugin.py:134: in _getobj
    return self._memoizedcall('_obj', self._importtestmodule)
E   AttributeError: 'DescribeBlock' object has no attribute '_memoizedcall'
```

I wrote a little example:

```python
import pytest


@pytest.fixture()
def truelness():
    return True

def describe_pytest_describe():
    def should_work_on_pytest_6():
        assert True


def describe_pytest_describe_with_fixture(truelness):
    def should_work_on_pytest_6():
        assert truelness is True
```

output:
```
================================================================================================================ ERRORS ================================================================================================================
________________________________________________________________________________________________ ERROR collecting tests/test_example.py ________________________________________________________________________________________________
.venv/lib/python3.9/site-packages/pytest_describe/plugin.py:134: in _getobj
    return self._memoizedcall('_obj', self._importtestmodule)
E   AttributeError: 'DescribeBlock' object has no attribute '_memoizedcall'

During handling of the above exception, another exception occurred:
.venv/lib/python3.9/site-packages/pytest_describe/plugin.py:136: in _getobj
    return self._importtestmodule()
.venv/lib/python3.9/site-packages/pytest_describe/plugin.py:144: in _importtestmodule
    module = make_module_from_function(self.funcobj)
.venv/lib/python3.9/site-packages/pytest_describe/plugin.py:37: in make_module_from_function
    module.__dict__.update(trace_function(funcobj))
.venv/lib/python3.9/site-packages/pytest_describe/plugin.py:19: in trace_function
    funcobj(*args, **kwargs)
E   TypeError: describe_pytest_describe_with_fixture() missing 1 required positional argument: 'truelness'
======================================================================================================= short test summary info ========================================================================================================
ERROR tests/test_example.py - TypeError: describe_pytest_describe_with_fixture() missing 1 required positional argument: 'truelness'

```

It looks like a problem with this specific commit in pytest: https://github.com/pytest-dev/pytest/commit/ceb016514b6b62cfe327db1cb5bdc3fef3244900

Could you please take a look?

**Comment by jacebrowning** [comment] 2020-10-24 15:09
@b0g3r are you able to reproduce this with the unreleased version in the `master` branch?

**Comment by ROpdebee** [comment] 2020-11-01 14:38
Not OP but can confirm the `_memoizedcall` error is gone on master for me (python 3.8.2, pytest 6.1.2). The example above still fails because the fixture isn't injected into the describe block, which I can reproduce on pytest 5.4.3 as well, although that may be a different issue.

**Comment by b0g3r** [comment] 2020-11-01 14:41
Oops, my bad, my intuition told me that it should work like this 🙇‍♂️

**Comment by ROpdebee** [comment] 2020-11-01 15:09
Fixture issue is related to #9 and #11, it's been a few years so it might be worthwhile to re-evaluate whether it'd be possible to inject fixtures into describe blocks (perhaps limited to class-scope fixtures?)

**Comment by Cito** [comment] 2021-08-18 17:31
This should be fixed in [2.0](https://github.com/pytest-dev/pytest-describe/releases/tag/2.0.0). The fixture issue is now covered in #38. Any help with that one is appreciated.

**Closed by Cito** 2021-08-18 17:31 UTC
